const bHabitPhrases = [
  'Keep going; you’re stronger than you think!',
  'Every step forward counts.',
  'You can do this; I believe in you.',
  "It's just a bump in the road.",
  'Progress is progress, no matter how small.',
  "You've got this; stay strong!",
  'Every day is a new opportunity.',
  "Don't be too hard on yourself.",
  'Small steps lead to big changes.',
  'You’re making progress, keep it up!',
  'Believe in your strength.',
  "One slip doesn't define you.",
  'Keep your eyes on the goal.',
  'Tomorrow is a new day.',
  'You are capable of amazing things.',
  'Each day is a fresh start.',
  'Don’t give up; keep pushing forward.',
  'Mistakes are part of the journey.',
  'You’re closer than you were yesterday.',
  'Every effort brings you closer.',
  'Stay positive; you’re doing great.',
  'Keep your head up; you’re on your way.',
  'Believe in your journey.',
  'You’re making a difference.',
  'Keep fighting; you’re worth it.',
  'Progress, not perfection.',
  'You have the power to change.',
  'Every day is a chance to improve.',
  'Stay determined; you’re getting there.',
  'Keep moving forward; you’re doing well.',
  'Your efforts are paying off.',
  'You’re stronger than your habits.',
  'Take it one day at a time.',
  'Believe in your ability to change.',
  'Keep your focus; you’re doing great.',
  'Every setback is a setup for a comeback.',
  'Stay motivated; you’re on the right track.',
  'You’re making positive changes.',
  'Keep striving; you’re almost there.',
  'You have the strength within you.',
  'Stay committed; you’re doing fantastic.',
  'You’re capable of overcoming this.',
  'Keep going; success is near.',
  'You’re transforming your life.',
  'Keep believing in yourself.',
  'Your persistence is inspiring.',
  'You’re on your way to greatness.',
  'Stay positive; you’re making progress.',
  'Keep your spirits high; you’re doing well.',
  'You’re not alone; keep pushing forward.',
];

const goodHabitPhrases = [
  'Great job! Keep it up!',
  "You're doing amazing work!",
  'Fantastic effort!',
  'Keep up the good work!',
  "You're on the right track!",
  'Way to go!',
  'You’re making great progress!',
  'Keep shining!',
  'Excellent dedication!',
  "You're doing wonderful!",
  'Outstanding effort!',
  'You’re setting a great example!',
  'Impressive work!',
  'You’re a star!',
  'Keep moving forward!',
  'You’re doing something amazing!',
  'You’re achieving your goals!',
  'Remarkable progress!',
  "You're an inspiration!",
  'Keep it up, you’re doing great!',
  'Superb job!',
  'You’re crushing it!',
  'You’re making a positive change!',
  'Keep that momentum going!',
  'Amazing perseverance!',
  'You’re on fire!',
  'Outstanding dedication!',
  'You’re reaching new heights!',
  'Keep striving for excellence!',
  "You're a powerhouse!",
  'Incredible progress!',
  'You’re making a difference!',
  'Excellent consistency!',
  'You’re unstoppable!',
  'Great persistence!',
  'You’re really pushing the limits!',
  'Keep achieving greatness!',
  "You're making your dreams come true!",
  'Keep that positive energy!',
  "You're succeeding every day!",
  'You’re doing phenomenally!',
  "You're a great example to others!",
  'You’re building great habits!',
  'Keep making progress!',
  'You’re doing an exceptional job!',
  'You’re really going places!',
  'Keep that determination!',
  'You’re an achiever!',
  'Keep up the fantastic work!',
];

export function getRandomGHabitPhrase() {
  const randomIndex = Math.floor(Math.random() * goodHabitPhrases.length);
  return goodHabitPhrases[randomIndex];
}

export function getRandomBHabitPhrase() {
  const randomIndex = Math.floor(Math.random() * bHabitPhrases.length);
  return bHabitPhrases[randomIndex];
}
